# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_catalogo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosMadre',
            fields=[
                ('id_datos_madre', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.TextField(blank=True, null=True)),
                ('hijos_vivos', models.TextField(blank=True, null=True)),
                ('hijos_nac_vivos', models.TextField(blank=True, null=True)),
                ('hijos_nac_muertos', models.TextField(blank=True, null=True)),
                ('estado_civil', models.TextField(blank=True, null=True)),
                ('etnia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datos_madre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefunFetal',
            fields=[
                ('id_defun_fetal', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('anio_def', models.IntegerField()),
                ('sem_gestac', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'defun_fetal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefunGeneral',
            fields=[
                ('id_defun_general', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('anio_nac', models.TextField(blank=True, null=True)),
                ('anio_def', models.IntegerField(blank=True, null=True)),
                ('edad', models.TextField(blank=True, null=True)),
                ('cod_edad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'defun_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDefFet',
            fields=[
                ('id_detalle_def_fet', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_detalle_fet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_def_fet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDefGen',
            fields=[
                ('id_detalle_def_gen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_detalle_gen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_def_gen',
                'managed': False,
            },
        ),
    ]
